services:
  - type: web
    name: colorspeak-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn colorspeak:application"  # Replace 'projectname' with your Django project folder
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
